spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost/library
    username: ad
    password: sa3r46es85
    driver-class-name: org.postgresql.Driver
  logging:
    level:
      org:
        springframework:
          security: DEBUG
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml